### PR TITLE
chore(ci): replace `npm ci` with npm `i` in publish step

### PR DESCRIPTION
**Pull request by valekjo**

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by B4nan — CHANGES_REQUESTED** [review]
Lets regenerate the lockfile too fix the install step.

**Comment by valekjo** [comment]
@B4nan I've replaced it in all install steps, did you mean that?

**Comment by vladfrangu** [comment]
> @B4nan I've replaced it in all install steps, did you mean that?

I don't think so, I think he meant run `npm i` locally and push the updated package-lock.json in this PR 👀

**Comment by B4nan** [comment]
One more thing, run `npx lerna ls --json | npx ts-node -T scripts/sync-root-changelog.ts` to update the changelog in root, that's the last step that wasn't done because of the failure.

**Comment by valekjo** [comment]
@B4nan done.

**Pull request merged**
