### PR TITLE
Add target=blank to external readme links

### PR DESCRIPTION
**Pull request by m-murasovs**

### CODE REVIEW

**Comment by mnmkng** [comment]
@B4nan not sure how you want to deal with this :) I guess we merge it, release and then update the new pacakges and destroy the world?

**Comment by B4nan** [comment]
sure, let's merge it and I'll rebase the huge one, should be easy

**Comment by m-murasovs** [comment]
@mnmkng @B4nan thanks lads! Can I leave this one with you?

**Comment by mnmkng** [comment]
We're only waiting for @jbartadev to approve it :)

**Comment by mtrunkat** [comment]
image

**Review by mnmkng — APPROVED** [review]

**Comment by mnmkng** [comment]
sorry @jbartadev 🚀

**Pull request merged**
