### PR TITLE
feat(consts): add INTEGRATIONS actor category

### PR DESCRIPTION
**Pull request by valekjo**

### CODE REVIEW

**Review by fnesveda — APPROVED** [review]

**Review by HonzaKirchner — APPROVED** [review]

**Comment by B4nan** [comment]
The build is apparently broken (probably some dependency update that requires newer node versions), without that the publishing won't work either... 

Ideally, I would just require node 18 everywhere and ship new major versions for every package, but I guess you still need node 16 supported for the console/api/etc?

**Comment by valekjo** [comment]
> The build is apparently broken (probably some dependency update that requires newer node versions), without that the publishing won't work either...
> 
> Ideally, I would just require node 18 everywhere and ship new major versions for every package, but I guess you still need node 16 supported for the console/api/etc?

We still need 14 for meteor :D

**Comment by B4nan** [comment]
We already discussed this with Pepa, IIRC we need npm@7 to have workspaces working, we don't need latest. Since it was working fine up until now, I would probably install v9 instead of v7.

**Comment by valekjo** [comment]
v9 also works, will go with that one.

**Pull request merged**
