### PR TITLE
feat: Increased length of actor name

### PR DESCRIPTION
**Pull request by drobnikj**
Increased the length of actor name into 63 chars (DNS safe string length)

### CODE REVIEW

**Review by mtrunkat — APPROVED** [review]

**Comment by mnmkng** [comment]
I don't understand the problem much, but why would an actor name, that's in the path part of URL need to be only 63 chars? Doesn't everyone use longer strings?

**Comment by mnmkng** [comment]
e.g. GitHub uses 100 chars for repository names

**Comment by drobnikj** [comment]
We discussed it with Mara and decided to go with DNS safe string to do not break in the future.
cc: https://github.com/apify/apify-core/issues/2792#issuecomment-853801044

**Comment by mnmkng** [comment]
Cool, will merge it when I get a confirmation from @B4nan that the deployment is fixed.

**Comment by B4nan** [comment]
Only way to find out is to merge it :D

**Comment by B4nan** [comment]
Works!

https://github.com/apify/apify-shared-js/releases

**Pull request merged**
